# This case study consists of 1000 marks and the solution file is expected to be submitted in the upcoming session for evaluation.

In [1]:
import numpy as np

### 1.Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [2]:
mat1 = np.arange(9).reshape(3,3)
mat2 = np.arange(9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1*mat2)


print("\nDivision\n------------------\n", mat1/mat2)
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", 3*mat1 - 2*mat2)


print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)


print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n",pow(mat1,0.5))


1st Matrix of random single-digit numbers
----------------------------------------
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Addition
------------------
 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]

Multiplication
------------------
 [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]

Division
------------------
 [[nan  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]

Linear combination: 3*A - 2*B
-----------------------------
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Addition of a scalar (100)
-------------------------
 [[100 101 102]
 [103 104 105]
 [106 107 108]]

Exponentiation, matrix cubed here
----------------------------------------
 [[  0   1   8]
 [ 27  64 125]
 [216 343 512]]

Exponentiation, mat1 sq-root using pow function
-------------------------------------------
 [[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]


C:\Users\panda4\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()


Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [3]:
from numpy.random import randint as ri
mat1 = ri(1,10,9).reshape(3,3)
mat2 = ri(1,10,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=0))


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=1))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.product(mat1,axis=1))


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.product(mat2,axis=0))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",np.mean(mat1))


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1))


mat1 = ri(1,99,9).reshape(3,3)
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.std(mat1))


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.var(mat1))


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[4 8 6]
 [7 1 5]
 [1 9 5]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[6 2 5]
 [5 5 3]
 [3 6 7]]

Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 46

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [12 18 16]

Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [18 13 15]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [192  35  45]

Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [ 90  60 105]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 5.111111111111111

Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 2

###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [9]:
##Solution
mat1 = ri(1,10,9).reshape(3,3)
print(mat1)
mat2 = mat1.reshape(9,1)
print(mat2)

[[7 4 6]
 [6 2 8]
 [2 5 2]]
[[7]
 [4]
 [6]
 [6]
 [2]
 [8]
 [2]
 [5]
 [2]]


### 4.Sort

In [10]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [61 37 96 47  3 15 94  4 43 74]

Here is the sorted vector
 -------------------------------------------------- 
 [ 3  4 15 37 43 47 61 74 94 96]


In [11]:
M = ri(1,100,25).reshape(5,5) #  5*5 Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M,axis=1)) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M,axis=0))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[62 45 90 63 14]
 [47 80 99 98 43]
 [14 98 54 72  8]
 [84 17 20 14 65]
 [79 40 20 12 37]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[14 45 62 63 90]
 [43 47 80 98 99]
 [ 8 14 54 72 98]
 [14 17 20 65 84]
 [12 20 37 40 79]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[14 17 20 12  8]
 [47 40 20 14 14]
 [62 45 54 63 37]
 [79 80 90 72 43]
 [84 98 99 98 65]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [14]:
# Fill the following ***** with appropriate solution.
a= ri(1,100,30).reshape(1,30)
b= ri(1,100,30).reshape(2,3,5)
c= ri(1,100,30).reshape(6,5)

print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:", a.max())
print("Max of b:",b.max())

print("Max of a location:", a.argmax())
print("Max of b location:", b.argmax())
print("Max of c location:", c.argmax())

print("Max of a:", a.max())
print("Max of b:", b.max())

print("Max of a location:", a.argmax())
print("Max of b location:", b.argmax())
print("Max of c location:", c.argmax())



a: [[62 57 53 70 86 96 78 25 56 22 12 61 57 86 98 64 92 34 88 77  1 60 36 13
  71 86 36 60 35 94]]
b: [[[83 97 12 56 72]
  [68 54 34 32  4]
  [35 80 90 86 91]]

 [[13 43 39 63 35]
  [98 52 27 84 43]
  [99 28 71 90 28]]]
c: [[46 63 44  4 44]
 [45 53 45 64 79]
 [48 73 60 39 12]
 [41 17 40 90 35]
 [73 69 17 14 75]
 [56 20 97 23 76]]
Max of a: 98
Max of b: 99
Max of a location: 14
Max of b location: 25
Max of c location: 27
Max of a: 98
Max of b: 99
Max of a location: 14
Max of b location: 25
Max of c location: 27


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [17]:

mat1 = ri(1,10,9).reshape(3,3)
mat2 = ri(1,10,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n", pow(mat1,0.5))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log(mat1))


print("\nModulo reminder using np\n",'-'*50,"\n", np.mod(mat1,mat2))




1st Matrix of random single-digit numbers
----------------------------------------
 [[3 4 5]
 [4 3 4]
 [3 6 1]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[9 9 9]
 [8 6 7]
 [6 3 3]]

Sq-root of 1st matrix using np
------------------
 [[1.73205081 2.         2.23606798]
 [2.         1.73205081 2.        ]
 [1.73205081 2.44948974 1.        ]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[ 20.08553692  54.59815003 148.4131591 ]
 [ 54.59815003  20.08553692  54.59815003]
 [ 20.08553692 403.42879349   2.71828183]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[1.09861229 1.38629436 1.60943791]
 [1.38629436 1.09861229 1.38629436]
 [1.09861229 1.79175947 0.        ]]

Modulo reminder using np
 -------------------------------------------------- 
 [[3 4 5]
 [4 3 4]
 [3 0 1]]


### 7.Generating matrices from distributions

In [19]:

print("Random number generation (from Uniform distribution)")
print(np.random.randn(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(2,3))

print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randn(2,3)) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.random.randn(2,3)) # 20 samples drawn from a dice throw

Random number generation (from Uniform distribution)
[[-0.82801424  1.65117841 -0.40102995]
 [-0.77778581  0.70646499  0.05661868]]
Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-1.20482204  0.33866095 -0.09907853]
 [-1.21516316  2.09326018 -0.71933715]]
Random integer vector: [63 11  2 69 90 37 94 60 41 32]

Random integer matrix
[[-0.78718009 -0.50279841 -0.06976998]
 [ 1.68685896  0.131714    1.75370386]]

20 samples drawn from a dice throw: [[-0.40418109 -0.30550123 -0.84646816]
 [ 1.11903732  1.88506151 -0.03331832]]


### 8.Find the nearest value from a given number in an array using NumPy.

In [29]:
#Steps
#Create an array of 5 random element from 1 to 12
#Suppose find the nearest values of 10 in an array so set value=10
#find the index where difference is minimum and get the element
import numpy as np
x = np.random.uniform(1, 12, 5)
v = 10
n = x.flat[np.abs(x - v).argmin()]
print(n)

9.360333725645965


### 9.Write code using numpy to produce following output
[[0 0 0] [0 1 2] [0 2 4]]

In [34]:
row_num = int(input("Input number of rows: "))
col_num = int(input("Input number of columns: "))
multi_list = [[0 for col in range(col_num)] for row in range(row_num)]

for row in range(row_num):
    for col in range(col_num):
        multi_list[row][col]= row*col

print(multi_list)

Input number of rows: 3
Input number of columns: 3
[[0, 0, 0], [0, 1, 2], [0, 2, 4]]
